create table users
(
    dtype           varchar(31)  not null,
    id              bigint generated by default as identity
        primary key,
    avatar          text,
    email           varchar(255) not null
        constraint uk6dotkott2kjsp8vw4d0m25fb7
            unique,
    first_name      varchar(255),
    login           varchar(255) not null
        constraint ukow0gan20590jrb00upg3va2fn
            unique,
    password        varchar(255) not null,
    patronymic_name varchar(255),
    role            varchar(255)
        constraint users_role_check
            check ((role)::text = ANY
        ((ARRAY ['CLIENT'::character varying, 'ADMIN'::character varying, 'DIRECTOR'::character varying])::text[])),
    second_name     varchar(255),
    address         varchar(255),
    income          double precision,
    mobile_phone    varchar(255)
);

alter table users
    owner to postgres;

create table accounts
(
    account_num      bigint generated by default as identity
        primary key,
    account_activity boolean,
    account_balance  numeric(38, 2),
    account_type     smallint
        constraint accounts_account_type_check
            check ((account_type >= 0) AND (account_type <= 3)),
    currency         varchar(255),
    open_date        date,
    client_id        bigint not null
        constraint fkbw5iulagxsv42cp190ccmfpsg
            references users
);

alter table accounts
    owner to postgres;

create table checking_account
(
    overdraft_limit numeric(38, 2),
    account_num     bigint not null
        primary key
        constraint fk9olcs24wyco0oo5ihud7o8wmg
            references accounts
);

alter table checking_account
    owner to postgres;

create table credit_account
(
    credit_limit numeric(38, 2),
    account_num  bigint not null
        primary key
        constraint fko456uf1yyib3pjwj526oqjiuj
            references accounts
);

alter table credit_account
    owner to postgres;

create table savings_account
(
    interest_rate numeric(38, 2),
    account_num   bigint not null
        primary key
        constraint fkbtnti5kac5c3phae3jor1heoc
            references accounts
);

alter table savings_account
    owner to postgres;

create table social_account
(
    social_payments boolean,
    account_num     bigint not null
        primary key
        constraint fk9s16jxhbd0uful2phlmpn4tsx
            references accounts
);

alter table social_account
    owner to postgres;

create table transactions
(
    id                   bigint generated by default as identity
        primary key,
    amount               numeric(38, 2),
    currency             varchar(255),
    transaction_time     timestamp(6),
    transaction_type     varchar(255)
        constraint transactions_transaction_type_check
            check ((transaction_type)::text = ANY
        ((ARRAY ['TRANSFER'::character varying, 'DEPOSIT'::character varying, 'WITHDRAWAL'::character varying])::text[])),
    recipient_account_id bigint
        constraint fk7p5py539o50atxdahncqqtibc
            references accounts,
    sender_account_id    bigint
        constraint fk68i6gd4um71kdv786gc5exkme
            references accounts
);

alter table transactions
    owner to postgres;

create table password_reset_token
(
    id          bigint generated by default as identity
        primary key,
    expiry_date timestamp(6),
    token       varchar(255),
    user_id     bigint
        constraint ukf90ivichjaokvmovxpnlm5nin
            unique
        constraint fk83nsrttkwkb6ym0anu051mtxn
            references users
);

alter table password_reset_token
    owner to postgres;

create table loan_request (
                              id bigint generated by default as identity primary key,
                              client_id bigint not null
                                  constraint fk_loan_request_client references users(id),
                              amount numeric(38, 2) not null,
                              term_in_months int not null,
                              purpose varchar(255),
                              request_date date not null,
                              status varchar(20) not null
                                  check (status in ('PENDING', 'APPROVED', 'REJECTED')),
                              reason varchar(255)
);

alter table loan_request owner to postgres;
